# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'merch-ui' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for merch-ui
  pod 'ABPadLockScreen'

  target 'merch-uiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'merch-uiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
